language: node_js
node_js: 6

cache:
  directories:
    - node_modules

os:
  - linux

before_script:
  - npm install
  - npm prune

script:
  - npm run make  

deploy:
  - provider: script
    script: deploy.sh $USERNAME $PASSWD $UPLOAD_LINK
  on:
    all_branches: true
