language: node_js
node_js: 9

cache:
  directories:
    - node_modules

os:
  - linux

before_script:
  - npm install
  - npm prune

script:
  - npm run build-deb

after_script:
  - ./deploy.sh $USERNAME $PASSWD $UPLOAD_LINK
