language: node_js
node_js: "node"

cache:
  directories:
    - node_modules

os:
  - linux

before_script:
  - npm install
  - npm prune
  - npm run build-guetzli-linux

script:
  - npm run make64

after_script:
  - ./deploy.sh $USERNAME $PASSWD $UPLOAD_LINK
