language: node_js
node_js: 6

cache:
  directories:
    - node_modules

os:
  - linux

addons:
  artifacts: true
    paths: 
  
  
install:
  - npm install
  
before_script:
  - npm prune
  
deploy:
  - provider: script
    script: deploy.sh $USERNAME $PASSWD $UPLOAD_LINK
  on:
    all_branches: true
script:
  - npm run make
