environment:
  nodejs_version: '8'

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - npm install npm -g
  - npm install
  - npm prune

test_script:
  - npm run test

build_script:
  - node --version
  - npm --version
  - npm run make64
  
artifacts:
  - path: out/make/squirrel.windows/x64/*.exe
    name: Guitzli_setup_win_x64
