environment:
  nodejs_version: '6'

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install npm -g
  - npm prune

test_script:
  - npm run test

build_script:
  - node --version
  - npm --version
  - npm run make
